### ISSUE TITLE
Providing package argument doesn't change generated documentation links 

### ISSUE THREAD

**Issue by yissachar** [nmorel/gwt-jackson-rest#1]
When providing a package argument to change the package of the generated files, the actual class package is changed correctly, but the documentation is linked. For example:

```
package com.foo.client;

/**
* Generated REST service builder for {@link com.foo.server.Api}.
*/
```

**Comment by nmorel** [comment]
I don't understand the issue. Why should the link change ? It is the base class used to generate the builder.

**Comment by yissachar** [comment]
Sorry, you are correct. The link showed up as an error in my IDE and I posted this issue without thinking things through. The real issue is that I am using a multi-project Gradle setup and the client code does not depend on the server code, and so cannot find the source for the documentation link.
