### ISSUE TITLE
Support for @Consumes and @Produces annotations

### ISSUE THREAD

**Issue by rsertelon** [nmorel/gwt-jackson-rest#11]
These annotations are important for resource matching. It would be nice if headers `Content-Type` and `Accept` could use their values automatically.

**Comment by rsertelon** [comment]
I think I've done something that works quite well, adding the first produces/consumes value to headers when necessary.

However, before submitting a PR, I'd like to discuss a case. Indeed, now that gwt-jackson-rest detects content types expected or produced by a REST method, it might also be able to detect when it won't be able to work properly.

For example, in a resource, if someone adds two methods with same method/path, but different `@Produces` they might want to have only the one with `application/json` (or `application/<anything_here>+json`) to be picked up by gwt-jackson-rest.

This seems logical as there's only support for JSON in the library, but a server could have multiple representations for the same resource.

I think the method should be skipped, just like you did with `isRestMethod` that make the method skipped if there's no `@GET` etc.

What do you think?

**Comment by nmorel** [comment]
Hi and thanks for the PR :)

For a start, we can just ignore the method not consuming/producing json.  
But maybe we could go a bit further. If a method doesn't produce json, we could still generate the method but return the text directly without deserializing the response.
And same for the consume part. Just expect a string body if post/put and let the user serialize it.

**Comment by rsertelon** [comment]
I'll go for the ignoring part, not sure I'll be able to dig further. I'll tell you when done ;)

**Comment by rsertelon** [comment]
I think it's good. At least it works as expected ;)
