### ISSUE TITLE
Path params never initialized

### ISSUE THREAD

**Issue by yissachar** [nmorel/gwt-jackson-rest#3]
I am trying to call an API with path params:

```
MyApiBuilder.getSomething()
  .addPathParam("foo", "bar")
  .send();
```

However this results in an NPE since in [RestRequestBuilder](https://github.com/nmorel/gwt-jackson-rest/blob/master/api/src/main/java/com/github/nmorel/gwtjackson/rest/api/RestRequestBuilder.java) the pathParams are never initialized.

**Comment by nmorel** [comment]
Ahah nice catch! I really need to add some tests to this project.

**Comment by nmorel** [comment]
Can you try the snapshot `0.2.2-SNAPSHOT` please ?

If it works and you don't find any other issue, I'll generate a new release.

**Comment by yissachar** [comment]
It works great now :+1:
