### ISSUE TITLE
Null query/path params not handled

### ISSUE THREAD

**Issue by yissachar** [nmorel/gwt-jackson-rest#4]
[RestRequestBuilder](https://github.com/nmorel/gwt-jackson-rest/blob/master/api/src/main/java/com/github/nmorel/gwtjackson/rest/api/RestRequestBuilder.java#L227) doesn't check for null params and exclude them from being added to the URL. Currently a null param is an NPE.

I have a method that takes a lot of different query params, however only a few are usually used. Due to the design of the generated API method, I am forced to pass in every param. It would be great if I could pass in null for a param to indicate that I don't want that param added to the URL for this request.

**Comment by nmorel** [comment]
Should be fixed in 0.3.1 :)

**Comment by yissachar** [comment]
Confirmed, it works now. Thanks for being so responsive!
